name: Deploy Dev
on:
   workflow_dispatch: {}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Build
        run: |
          yarn
          yarn prepare
          yarn build:dev

      - name: Deploy
        run: |
          aws s3 cp apps/portal/dist/pby s3://a1-buyer-portal --recursive
          aws cloudfront create-invalidation --distribution-id EOKG6RLFTY9T9 --path "/*"